version: '3.8'

services:
  app:
    build: .
    container_name: student_platform-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: jdbc:postgresql://postgres-local:5432/university_platform
      REDIS_HOST: redis-local
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka-local:29092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres-local:
        condition: service_healthy
      redis-local:
        condition: service_started
      kafka-local:
        condition: service_started

  kafka-local:
    image: apache/kafka:latest
    container_name: kafka-local
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-local:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-local:9093
      KAFKA_OFFER_MAX_MS: 60000
  postgres-local:
    image: postgres:15-alpine
    container_name: postgres-local
    restart: always
    environment:
      POSTGRES_DB: university_platform
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"
    volumes:
      - postgres_platform_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d university_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-local:
    image: redis:7-alpine
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_platform_data:
  redis_data: