spring.application.name=anonymous-student-platform

#DATABASE
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.secret=${JWT_TOKEN}
jwt.expiration=${EXPIRATION}

#Files
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=uploads/materials

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
