spring.application.name=anonymous-student-platform

#DATABASE
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

#JWT
jwt.secret=${JWT_TOKEN}
jwt.expiration=${EXPIRATION}
