spring.application.name=anonymous-student-platform

spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update